### PR TITLE
Vs2012support

### PR DESCRIPTION
**Pull request by staffann**
Updated to work for all versions VS2010 to 2015. 
Now built with VS2015 RC (I used the community version).
Since Ctrl-K Ctrl-O is used by a standard command in BS2013 and forwards (open corresponding header/source file) I changed the default to Ctrl-K Ctrl-0 (zero).

I like this extension and would very much like to see it support all existing and future versions. Please let me know any comments.

### CODE REVIEW

**Comment by martinky** [comment]
Hi Staffan and thank you for your contribution!

**Comment by Mpdreamz** [comment]
Hey @martinky mind releasing it on the gallery as well?

**Comment by martinky** [comment]
Hey. Not at the moment. Is anyone still using this? Since in VS2013 you have Ctrl+, out of the box, which although not perfect, is a nice way to jump to file.

**Comment by staffann** [comment]
Ctrl+, is nice, but in a large project I much prefer this to find the correct file to open. You get just the files and not all other symbols which can be too much in a large project. Me and my collegues at work use it all of the time. I wouldn't have made the effort to update otherwise. I'd like it very much if it was released in the gallery. Only one entry needed for all VS versions 2010 to 2015.

**Comment by martinky** [comment]
OK then, one of these days I'll look into it. I'll write here when it's published.

**Comment by Mpdreamz** [comment]
Agreed ctrl+, is just at that border of noticeably slow and the other quick open file extensions currently available for vs2015 are either too feature rich or simply fail to list all the files in the solution.

**Pull request merged**
